spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      group-id: TestTaskConsumer2Application
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: 1:com.example.testtaskproducer.dto.StringDto,2:com.example.testtaskconsumer2.dto.StringDto
server:
  port: 9094

kafka-topic:
  strings-under-100: strings.under.100
